// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYRsCD8gx5PxQHTjT7exm_bpvhwRefxFI',
    appId: '1:463692732659:web:9b3c994770e70efe3cff86',
    messagingSenderId: '463692732659',
    projectId: 'zarq-messenger',
    authDomain: 'zarq-messenger.firebaseapp.com',
    storageBucket: 'zarq-messenger.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDysX-_VI4BJjviLhDtouZX10mJIiXOQ7c',
    appId: '1:463692732659:android:35d62248982fe8ad3cff86',
    messagingSenderId: '463692732659',
    projectId: 'zarq-messenger',
    storageBucket: 'zarq-messenger.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYRsCD8gx5PxQHTjT7exm_bpvhwRefxFI',
    appId: '1:463692732659:web:9c9e540fc154b8743cff86',
    messagingSenderId: '463692732659',
    projectId: 'zarq-messenger',
    authDomain: 'zarq-messenger.firebaseapp.com',
    storageBucket: 'zarq-messenger.firebasestorage.app',
  );
}
