package com.zarq.messenger

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import android.util.Log
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * SignalCrypto - Handles secure key storage using Android Keystore
 * Provides encryption/decryption for sensitive Signal Protocol data
 */
class SignalCrypto(private val context: Context) {

    companion object {
        private const val TAG = "SignalCrypto"
        private const val KEYSTORE_PROVIDER = "AndroidKeyStore"
        private const val KEY_ALIAS = "zarq_signal_master_key"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
        private const val GCM_IV_LENGTH = 12
        private const val GCM_TAG_LENGTH = 16
    }

    private var keyStore: KeyStore? = null
    private var masterKey: SecretKey? = null

    init {
        initializeKeystore()
    }

    /**
     * Initialize Android Keystore and generate master key if needed
     */
    private fun initializeKeystore() {
        try {
            Log.d(TAG, "Initializing Android Keystore...")

            // Load Android Keystore
            keyStore = KeyStore.getInstance(KEYSTORE_PROVIDER)
            keyStore?.load(null)

            // Check if master key exists, generate if not
            if (!keyStore?.containsAlias(KEY_ALIAS)!!) {
                Log.d(TAG, "Generating new master key in Android Keystore")
                generateMasterKey()
            } else {
                Log.d(TAG, "Loading existing master key from Android Keystore")
            }

            // Load the master key
            masterKey = keyStore?.getKey(KEY_ALIAS, null) as? SecretKey

            if (masterKey != null) {
                Log.d(TAG, "Android Keystore initialized successfully")
            } else {
                throw Exception("Failed to load master key")
            }

        } catch (e: Exception) {
            Log.e(TAG, "Failed to initialize Android Keystore", e)
            // Note: Calling code should handle this and fall back to unencrypted storage
            throw Exception("Keystore initialization failed: ${e.message}")
        }
    }

    /**
     * Generate a new AES master key in Android Keystore
     */
    private fun generateMasterKey() {
        try {
            val keyGenerator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, KEYSTORE_PROVIDER)

            val keyGenParameterSpec = KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                // Require authentication for key use (if device has secure lock screen)
                .setUserAuthenticationRequired(false) // Set to true for additional security
                .setRandomizedEncryptionRequired(true)
                .build()

            keyGenerator.init(keyGenParameterSpec)
            keyGenerator.generateKey()

            Log.d(TAG, "Master key generated successfully in Android Keystore")

        } catch (e: Exception) {
            Log.e(TAG, "Failed to generate master key", e)
            throw Exception("Master key generation failed: ${e.message}")
        }
    }

    /**
     * Encrypt data using Android Keystore master key
     */
    fun encryptData(plaintext: String): String {
        return try {
            if (masterKey == null) {
                throw Exception("Master key not available")
            }

            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.ENCRYPT_MODE, masterKey)

            // Get the IV generated by GCM mode
            val iv = cipher.iv

            // Encrypt the data
            val ciphertext = cipher.doFinal(plaintext.toByteArray(Charsets.UTF_8))

            // Combine IV + ciphertext and encode as base64
            val combined = iv + ciphertext
            val encoded = Base64.encodeToString(combined, Base64.NO_WRAP)

            Log.d(TAG, "Data encrypted successfully (${plaintext.length} -> ${encoded.length} chars)")
            encoded

        } catch (e: Exception) {
            Log.e(TAG, "Failed to encrypt data", e)
            throw Exception("Encryption failed: ${e.message}")
        }
    }

    /**
     * Decrypt data using Android Keystore master key
     */
    fun decryptData(encryptedData: String): String {
        return try {
            if (masterKey == null) {
                throw Exception("Master key not available")
            }

            // Decode from base64
            val combined = Base64.decode(encryptedData, Base64.NO_WRAP)

            // Extract IV and ciphertext
            val iv = combined.sliceArray(0 until GCM_IV_LENGTH)
            val ciphertext = combined.sliceArray(GCM_IV_LENGTH until combined.size)

            // Initialize cipher for decryption
            val cipher = Cipher.getInstance(TRANSFORMATION)
            val spec = GCMParameterSpec(GCM_TAG_LENGTH * 8, iv)
            cipher.init(Cipher.DECRYPT_MODE, masterKey, spec)

            // Decrypt the data
            val plaintext = cipher.doFinal(ciphertext)
            val decrypted = String(plaintext, Charsets.UTF_8)

            Log.d(TAG, "Data decrypted successfully (${encryptedData.length} -> ${decrypted.length} chars)")
            decrypted

        } catch (e: Exception) {
            Log.e(TAG, "Failed to decrypt data", e)
            throw Exception("Decryption failed: ${e.message}")
        }
    }

    /**
     * Check if Android Keystore encryption is available
     */
    fun isKeystoreAvailable(): Boolean {
        return try {
            masterKey != null && keyStore?.containsAlias(KEY_ALIAS) == true
        } catch (e: Exception) {
            Log.w(TAG, "Keystore availability check failed", e)
            false
        }
    }

    /**
     * Clear all keys from Android Keystore (for logout/reset)
     */
    fun clearKeys() {
        try {
            Log.d(TAG, "Clearing keys from Android Keystore...")

            keyStore?.deleteEntry(KEY_ALIAS)
            masterKey = null

            Log.d(TAG, "Keys cleared from Android Keystore")

        } catch (e: Exception) {
            Log.e(TAG, "Failed to clear keys from Keystore", e)
            // Not critical - continue with cleanup
        }
    }

    /**
     * Test encryption/decryption functionality
     */
    fun testEncryption(): Boolean {
        return try {
            val testData = "test_encryption_${System.currentTimeMillis()}"
            val encrypted = encryptData(testData)
            val decrypted = decryptData(encrypted)

            val success = (testData == decrypted)
            Log.d(TAG, "Encryption test ${if (success) "PASSED" else "FAILED"}")
            success

        } catch (e: Exception) {
            Log.e(TAG, "Encryption test failed", e)
            false
        }
    }

    /**
     * Get encryption information for debugging
     */
    fun getEncryptionInfo(): Map<String, Any> {
        return try {
            mapOf<String, Any>(
                "keystore_available" to isKeystoreAvailable(),
                "master_key_exists" to (masterKey != null),
                "key_alias" to KEY_ALIAS,
                "encryption_algorithm" to TRANSFORMATION,
                "key_size" to if (masterKey != null) "256-bit AES" else "unknown",
                "test_result" to testEncryption()
            )
        } catch (e: Exception) {
            Log.e(TAG, "Failed to get encryption info", e)
            mapOf<String, Any>(
                "error" to (e.message ?: "unknown_error"),
                "keystore_available" to false
            )
        }
    }
}